### ISSUE TITLE
_ breaks discord

### ISSUE THREAD

**Issue by ghost** [corsaroquad/DiteCross#1]
http://u.rubixy.com/u/41c0a1c6.png

**Comment by ghost** [comment]
If a message contains the '_' char it won't send the discord msg to telegram.

**Comment by TobiTenno** [comment]
interesting
you also can't wipe a channel from it, either.

**Comment by ghost** [comment]
Rebooting wipes all connected channels, and you have to do another handshake, which is the most retarded thing,  so been slowly moving to https://github.com/trgwii/TediCross , more active developed
